#pragma once
#include "arc.h"

typedef struct _DEVICE_ENTRY DEVICE_ENTRY, *PDEVICE_ENTRY;

typedef struct _DEVICE_VECTORS {
    PARC_CLOSE_ROUTINE Close;
    PARC_MOUNT_ROUTINE Mount;
    PARC_OPEN_ROUTINE_INTERNAL Open;
    PARC_READ_ROUTINE_INTERNAL Read;
    PARC_READ_STATUS_ROUTINE GetReadStatus;
    PARC_SEEK_ROUTINE Seek;
    PARC_WRITE_ROUTINE_INTERNAL Write;
    PARC_GET_FILE_INFO_ROUTINE GetFileInformation;
    PARC_SET_FILE_INFO_ROUTINE SetFileInformation;
    PARC_GET_DIRECTORY_ENTRY_ROUTINE_INTERNAL GetDirectoryEntry;
} DEVICE_VECTORS, *PDEVICE_VECTORS;

struct _DEVICE_ENTRY {
	CONFIGURATION_COMPONENT Component;
	PCM_PARTIAL_RESOURCE_LIST_HEADER ConfigData;
	PDEVICE_ENTRY Peer, Child, Parent;
    PDEVICE_VECTORS Vectors;
    // todo what else?
};
